# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/Desktop/Lane

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/Desktop/Lane

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/Desktop/Lane/CMakeFiles /home/ubuntu/Desktop/Lane/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/Desktop/Lane/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named i2c-pwm

# Build rule for target.
i2c-pwm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 i2c-pwm
.PHONY : i2c-pwm

# fast build rule for target.
i2c-pwm/fast:
	$(MAKE) -f LIBSCAR/peripheral_driver/i2c/CMakeFiles/i2c-pwm.dir/build.make LIBSCAR/peripheral_driver/i2c/CMakeFiles/i2c-pwm.dir/build
.PHONY : i2c-pwm/fast

#=============================================================================
# Target rules for targets named kinect-cv2

# Build rule for target.
kinect-cv2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kinect-cv2
.PHONY : kinect-cv2

# fast build rule for target.
kinect-cv2/fast:
	$(MAKE) -f LIBSCAR/stereo_vision/CMakeFiles/kinect-cv2.dir/build.make LIBSCAR/stereo_vision/CMakeFiles/kinect-cv2.dir/build
.PHONY : kinect-cv2/fast

#=============================================================================
# Target rules for targets named test-kinect-cv2

# Build rule for target.
test-kinect-cv2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-kinect-cv2
.PHONY : test-kinect-cv2

# fast build rule for target.
test-kinect-cv2/fast:
	$(MAKE) -f LIBSCAR/stereo_vision/CMakeFiles/test-kinect-cv2.dir/build.make LIBSCAR/stereo_vision/CMakeFiles/test-kinect-cv2.dir/build
.PHONY : test-kinect-cv2/fast

#=============================================================================
# Target rules for targets named test-kinect-cv2-2

# Build rule for target.
test-kinect-cv2-2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-kinect-cv2-2
.PHONY : test-kinect-cv2-2

# fast build rule for target.
test-kinect-cv2-2/fast:
	$(MAKE) -f LIBSCAR/stereo_vision/CMakeFiles/test-kinect-cv2-2.dir/build.make LIBSCAR/stereo_vision/CMakeFiles/test-kinect-cv2-2.dir/build
.PHONY : test-kinect-cv2-2/fast

#=============================================================================
# Target rules for targets named HAL

# Build rule for target.
HAL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HAL
.PHONY : HAL

# fast build rule for target.
HAL/fast:
	$(MAKE) -f LIBSCAR/HAL/CMakeFiles/HAL.dir/build.make LIBSCAR/HAL/CMakeFiles/HAL.dir/build
.PHONY : HAL/fast

#=============================================================================
# Target rules for targets named openni2

# Build rule for target.
openni2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openni2
.PHONY : openni2

# fast build rule for target.
openni2/fast:
	$(MAKE) -f LIBSCAR/openni2/CMakeFiles/openni2.dir/build.make LIBSCAR/openni2/CMakeFiles/openni2.dir/build
.PHONY : openni2/fast

#=============================================================================
# Target rules for targets named traffic

# Build rule for target.
traffic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 traffic
.PHONY : traffic

# fast build rule for target.
traffic/fast:
	$(MAKE) -f traffic/CMakeFiles/traffic.dir/build.make traffic/CMakeFiles/traffic.dir/build
.PHONY : traffic/fast

#=============================================================================
# Target rules for targets named lanedetec

# Build rule for target.
lanedetec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lanedetec
.PHONY : lanedetec

# fast build rule for target.
lanedetec/fast:
	$(MAKE) -f include/CMakeFiles/lanedetec.dir/build.make include/CMakeFiles/lanedetec.dir/build
.PHONY : lanedetec/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... i2c-pwm"
	@echo "... test-kinect-cv2-2"
	@echo "... kinect-cv2"
	@echo "... test-kinect-cv2"
	@echo "... HAL"
	@echo "... openni2"
	@echo "... traffic"
	@echo "... lanedetec"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

